@Library('mylibrary')_
pipeline
{
    agent any
    stages
    {
        stage('Continuous Download_master')
        {
            steps
            {
                script
                {
                  cicd.newGit("https://github.com/su-hasini/maven.git")
                }
            }
        }
        stage('ContinuousBuild_master')
        {
            steps
            {
                script
                {
                    cicd.newMaven()
                }
            }    
        }
        stage('conti.deploy_master')
        {
            steps
            {
                script
                {
                    cicd.newDeploy("sharedlibrarywithdeclarativepipeline","172.31.86.200","testapp")
                }
            }
        }
        stage('conti.Testing_master')
        {
            steps
            {
                script
                {
                    cicd.newGit("https://github.com/su-hasini/functionaltesting.git")
                    cicd.runSelenium("sharedlibrarywithdeclarativepipeline")
                }
            }
        }
        stage('conti.delivery_master')
        {
            steps
            {
                script
                {
                    cicd.newDeploy("sharedlibrarywithdeclarativepipeline","172.31.86.63","prodapp")
                }
            }
        }
    }
}
